builders:
  mariana:
    target: ":mariana"
    import: "package:mariana_flutter_compiler/MarianaCompilerBuilder.dart"
    builder_factories: ["starterBuilder"]
    build_extensions: { ".dart": [".mariana.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]